#!/usr/bin/env node
/**
 * Guide generator — produces/updates integration-guide.md and deployment-guide.md
 * by injecting live values from .env.example and package.json.
 *
 * Usage:
 *   node scripts/generate-guides.mjs
 *   node scripts/generate-guides.mjs --dry-run   # print diffs, no writes
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DRY_RUN = process.argv.includes('--dry-run');

// ── helpers ───────────────────────────────────────────────────────────────────

function read(rel) {
  const p = join(ROOT, rel);
  return existsSync(p) ? readFileSync(p, 'utf8') : '';
}

function write(rel, content) {
  const p = join(ROOT, rel);
  if (DRY_RUN) {
    console.log(`[dry-run] Would write ${rel} (${content.length} bytes)`);
    return;
  }
  writeFileSync(p, content, 'utf8');
  console.log(`✔  Updated ${rel}`);
}

function parseEnvExample(src) {
  const vars = {};
  for (const line of src.split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) vars[m[1]] = m[2].replace(/^"|"$/g, '');
  }
  return vars;
}

function getVersion() {
  try {
    return JSON.parse(read('package.json')).version ?? 'unknown';
  } catch {
    return 'unknown';
  }
}

// ── data ──────────────────────────────────────────────────────────────────────

const env = parseEnvExample(read('.env.example'));
const version = getVersion();
const generated = `<!-- Generated by scripts/generate-guides.mjs — do not edit manually -->\n<!-- Version: ${version} | Generated: ${new Date().toISOString()} -->\n\n`;

// ── environment config table ──────────────────────────────────────────────────

const envTable = `
| Variable | Default | Description |
|----------|---------|-------------|
${Object.entries(env).map(([k, v]) => `| \`${k}\` | \`${v || '(empty)'}\` | See \`.env.example\` |`).join('\n')}
`.trim();

// ── network config blocks ─────────────────────────────────────────────────────

const networks = {
  local: {
    VITE_STELLAR_NETWORK: 'local',
    VITE_SOROBAN_RPC_URL: 'http://localhost:8000',
    VITE_HORIZON_URL: 'http://localhost:8001',
    VITE_NETWORK_PASSPHRASE: 'Standalone Network ; February 2017',
  },
  testnet: {
    VITE_STELLAR_NETWORK: 'testnet',
    VITE_SOROBAN_RPC_URL: 'https://soroban-testnet.stellar.org',
    VITE_HORIZON_URL: 'https://horizon-testnet.stellar.org',
    VITE_NETWORK_PASSPHRASE: 'Test SDF Network ; September 2015',
  },
  mainnet: {
    VITE_STELLAR_NETWORK: 'mainnet',
    VITE_SOROBAN_RPC_URL: 'https://soroban.stellar.org',
    VITE_HORIZON_URL: 'https://horizon.stellar.org',
    VITE_NETWORK_PASSPHRASE: 'Public Global Stellar Network ; September 2015',
  },
};

function envBlock(vars) {
  return Object.entries(vars).map(([k, v]) => `${k}=${v}`).join('\n');
}

// ── inject into existing guides ───────────────────────────────────────────────

/**
 * Replace a tagged section in a markdown file.
 * Tags: <!-- GEN:section-name --> ... <!-- /GEN:section-name -->
 */
function inject(content, tag, replacement) {
  const re = new RegExp(`<!-- GEN:${tag} -->[\\s\\S]*?<!-- /GEN:${tag} -->`, 'g');
  const block = `<!-- GEN:${tag} -->\n${replacement}\n<!-- /GEN:${tag} -->`;
  return re.test(content) ? content.replace(re, block) : content;
}

// ── integration guide ─────────────────────────────────────────────────────────

let integration = read('docs/integration-guide.md');

// Inject env table if tag present, otherwise append a version footer
integration = inject(integration, 'env-table', envTable);
integration = inject(integration, 'version', `_Guide version: **${version}** — auto-updated by \`generate-guides.mjs\`_`);

// Append version footer if not already present
if (!integration.includes('<!-- generated-footer -->')) {
  integration += `\n\n<!-- generated-footer -->\n_Last generated: ${new Date().toISOString()} | Kit version: ${version}_\n`;
}

write('docs/integration-guide.md', integration);

// ── deployment guide ──────────────────────────────────────────────────────────

let deployment = read('docs/deployment-guide.md');

for (const [name, vars] of Object.entries(networks)) {
  deployment = inject(deployment, `env-${name}`, `\`\`\`env\n${envBlock(vars)}\n\`\`\``);
}

deployment = inject(deployment, 'env-table', envTable);
deployment = inject(deployment, 'version', `_Guide version: **${version}** — auto-updated by \`generate-guides.mjs\`_`);

if (!deployment.includes('<!-- generated-footer -->')) {
  deployment += `\n\n<!-- generated-footer -->\n_Last generated: ${new Date().toISOString()} | Kit version: ${version}_\n`;
}

write('docs/deployment-guide.md', deployment);

// ── summary ───────────────────────────────────────────────────────────────────

console.log(`\nGuide generation complete (version ${version})${DRY_RUN ? ' [dry-run]' : ''}`);
